#!/bin/sh
set -euo pipefail
IFS=$'\n\t'

sed -i '/^\[comment\]: # \(.*pre-commit.*\)/q' ./README.md
echo '```Hack' >> README.md
tree -F -n -x --dirsfirst . >> README.md
echo '```' >> README.md
git add README.md
